{% set name = "kombine" %}
{% set version = "0.8.4" %}
{% set sha256 = "4fc1f55e106ed93058b7241aae254f3db5fd907a7cdf7a01e4b0a1968cafd382" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy

test:
  requires:
    - nose
  imports:
    - kombine
  commands:
    - nosetests kombine

about:
  home: https://github.com/bfarr/kombine
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: An embarrassingly parallel, kernel-density-based ensemble sampler
  description: |
    kombine is an ensemble sampler that uses a clustered
    kernel-density-estimate proposal density, allowing for
    massive parallelization and efficient sampling.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - bfarr
