travis:
  secure:
    BINSTAR_TOKEN: bT9pVF0vHUCU7pT+46m7GIW4WfhNjsC0jXsc1rQ1SD04fKAzvU4im92gXioTSoN/qX90mJOxPHou82zYvFSOCdFgRTGNRsPYak+aOjTpuxcDx+v6qaAAnDEuxrKtLlWdAjU5Baah0fnl4aS7eFp3eE3Io3IN3w/ovO73dNQKq9K5hgkFg45EmjacDigC6Mq1RWrxaZUzShLpOriFpy8clysYb1LyCViepUCVwAb/eCMPq33IBOEM2vk0/pi25TH1smrZGu9XY24ZTu591j/Y4AXrlORkpjJl1qslTrat1RnGh+cd6y+co2k15INGGVYwb74wDJxDwfmmEJdZBscyq1r0fU1yrP04QcxnZ2jf0y5+COQ67NLLXpPClgB2sb5oS9eVQzffk/nvLDoKnakqu5H7yS/ydfq65WCiLeC1VQWVj9BRXOrS1mSA4Siekw2hcymlCP76/TdfpLZQQEagCJLT5sKt6G0OsqBA7jq6n1KZHLhnuNrNkh2E9zmjczs/0Ky1l4jBYK3x/a0+0Y0rLnG830CJvR8GQ2Hlau5hRZrO2KYxEe/tjzHpmGg/aiNQBKJtd5JEthfUU+6GhHpmmjC8lJCazY67yyKtRVenVCtCkFPjj4LY2mAs7QfptgmjB9m2bJXCal7URfIpyBkLxcoX/Ktgq5AYy0qEI7e+QOE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
