travis:
  secure:
    BINSTAR_TOKEN: dNlD3r3WHjbn9iyDlPixzzSaBA+I+DpSFh/FLsZr9vAZLhzr1qUFRyPo0IpET1Jk1CwFnNsGFc/tAJHjTBGgQRIlb3e6wviBwsoFmhrnpTI43m4/7ji9g1oG/NEl1CyK55PfivwPxdRXR8lMl/hWpf0MigepWOqsdW6gsHXnm/86n8zfVeeTZyEWxhcemzdu+lCwK0a8JZ/OvBD0ybBqX8Y2A1tTIAZ0pEgFYZKsLcf8pnqRYax5ut9IGK9BK85BBZO6Q7qGLCUS+4/nUPMZ5Xr8d4vRmSy0tRk7mG7zI2mZs0zefv8/0o3Ju7TTHd3OniTDcGiH0H+ZIqIO8s5vC7vcSpFlGM8enCxfimEGo3PbvEwP0N8iTgvrHEibzTDUZxsLHQ5WM4X5CD+Ujk2NOOYlkk7+00cex2GbyerqZYMRcDvvn5ubTp8GfpgK8XvlRSZglAmdHAcYEVFzYV3Wfy+MqhOOuqQRWs68WX7Oyml3fVmqHW23IF7hScaPqvP1YtAeMH79SpnrLNRKwbDc2hsaBvIODfn5JwS3O2Yo33QMqabZmMPCzwotgdJaS1S6fTraA7c6LMPSysE980RZqfHOVvjmXw+rPHloY2jEwg1g/jGAoRIBbH8DIgxsu3NZoUOlTfUmSdJvRy/l2ijfeHKRRUEnHc/bMlcE5b77x2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
